name: weather_fox
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  intl: any
  weather_icons: 3.0.0
  http: ^1.1.2
  calendar_view: 1.0.4
  
  json_theme: ^4.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  logo_n_spinner: ^0.1.5
  # riverpod stuff
  flutter_riverpod: ^2.4.3
  riverpod_annotation: ^2.2.0

  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  logger: ^2.0.2
  go_router: ^13.0.1
  gap: ^3.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  hooks_riverpod: ^2.4.9
  get: ^4.6.6
  device_calendar: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  # riverpod generator/dev stuff
  riverpod_generator: ^3.0.0-dev.3
  riverpod_lint: ^2.3.0
  # import custom_lint too as riverpod_lint depends on it
  custom_lint:
  very_good_analysis: ^5.1.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/appainter_theme.json
  uses-material-design: true
  # for localization
  generate: true
